/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gpa.game;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.JLayeredPane;

/**
 *
 * @author ahmed
 */
public class MainMenu extends javax.swing.JPanel implements ActionListener {
    private JFrame frame;
    private CardLayout cardLayout;
    private JPanel cards; 
    private Timer timer;
    private ArrayList<Grade> grades;
    StateManager stateManager;
    
    public MainMenu(JFrame frame, CardLayout layout, JPanel cards) {
        this.frame = frame;
        this.cards = cards;
        this.cardLayout = layout;
        this.grades = new ArrayList<>();
        this.timer = new Timer(16, this);

        initComponents();
        timer.start(); // Start the animation timer
        this.stateManager = new StateManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        foreground = new javax.swing.JPanel();
        leaderboardButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                //        setOpaque(false); // Make the panel transparent
                for (Grade grade : grades) {
                    grade.draw(g); // Draw falling grades
                }
            }};

            setPreferredSize(new java.awt.Dimension(800, 600));

            jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));
            jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 600));

            foreground.setBackground(new java.awt.Color(51, 51, 51));
            foreground.setOpaque(false);

            leaderboardButton.setBackground(new java.awt.Color(51, 51, 255));
            leaderboardButton.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
            leaderboardButton.setForeground(new java.awt.Color(255, 255, 255));
            leaderboardButton.setText("Leader Board");
            leaderboardButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    leaderboardButtonActionPerformed(evt);
                }
            });

            exitButton.setBackground(new java.awt.Color(51, 51, 255));
            exitButton.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
            exitButton.setForeground(new java.awt.Color(255, 255, 255));
            exitButton.setText("Exit");
            exitButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitButtonActionPerformed(evt);
                }
            });

            startButton.setBackground(new java.awt.Color(51, 51, 255));
            startButton.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
            startButton.setForeground(new java.awt.Color(255, 255, 255));
            startButton.setText("Start Game");
            startButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    startButtonActionPerformed(evt);
                }
            });

            jLabel1.setBackground(new java.awt.Color(0, 0, 0));
            jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("GPA Game");

            javax.swing.GroupLayout foregroundLayout = new javax.swing.GroupLayout(foreground);
            foreground.setLayout(foregroundLayout);
            foregroundLayout.setHorizontalGroup(
                foregroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(foregroundLayout.createSequentialGroup()
                    .addGap(270, 270, 270)
                    .addGroup(foregroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(leaderboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(270, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foregroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            foregroundLayout.setVerticalGroup(
                foregroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(foregroundLayout.createSequentialGroup()
                    .addGap(147, 147, 147)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(85, 85, 85)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(leaderboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(757, Short.MAX_VALUE))
            );

            background.setBackground(new java.awt.Color(51, 51, 51));
            background.setForeground(new java.awt.Color(0, 0, 0));
            background.setPreferredSize(new java.awt.Dimension(800, 600));

            javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
            background.setLayout(backgroundLayout);
            backgroundLayout.setHorizontalGroup(
                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 800, Short.MAX_VALUE)
            );
            backgroundLayout.setVerticalGroup(
                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 600, Short.MAX_VALUE)
            );

            jLayeredPane1.setLayer(foreground, javax.swing.JLayeredPane.PALETTE_LAYER);
            jLayeredPane1.setLayer(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
            jLayeredPane1.setLayout(jLayeredPane1Layout);
            jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(foreground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );
            jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(foreground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 600, Short.MAX_VALUE)))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
        }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param g
     */
//    @Override
//    public void paintComponent(Graphics g) {
//        super.paintComponent(g);
//        
//        // Draw grade
//        for (Grade grade : grades) {
//            grade.draw(g);
//        }
//    }
    
    @Override
    public void actionPerformed(ActionEvent ae) {
        for (Grade grade : grades) {
            
            // Update grade positions
            grade.moveGrade();
            
            // Remove grade if it falls out
            if (grade.y > 600) {
                grades.remove(grade);
                break;
            }
        }
        
        if (new Random().nextInt(100) < 5) { // 5% chance to spawn a grade per frame
            grades.add(GradeFactory.getRandomGrade());
        }
        
        background.repaint();
    }
    
    
    private void leaderboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardButtonActionPerformed
        stateManager.leaderboardState(cardLayout, cards);
    }//GEN-LAST:event_leaderboardButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        stateManager.exitState(cardLayout , cards);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        stateManager.startState(cardLayout, cards);     
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel foreground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton leaderboardButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables


}
